# Arduino Definitions ##################################################################################################
########################################################################################################################

ARDUNIO_PORT = 'COM4'
COMMON_PORTS = ['COM1', 'COM2', 'COM3', 'COM4', 'COM5', 'COM6', 'COM7', 'COM8', 'COM9']
ARDUINO_BAUD_RATE = 9600

TIMEOUT = 5000  # in ms
REFRESH_DELAY = 100  # in ms
MS_CONV = 0.001
SEQUENCE_COUNT_MAX = 0xff

# Message definitions ##################################################################################################
########################################################################################################################

LEN_MSG_HEADER = 4  # Number of bytes in message header
LEN_MSG_FOOTER = 1  # Number of bytes in message header

IND_HEADER_ID = 0  # Number of bytes in message header
IND_CMD_ID = 1  # Number of bytes in message header
IND_SEQ_COUNT = 2  # Number of bytes in message header
IND_SIZE = 3  # Number of bytes in message header
IND_FOOTER = -1  # Number of bytes in message header
IND_RETURN_CODE = LEN_MSG_HEADER

EMPTY = []

HEADER_ID = 0x61
FOOTER_ID = 0x63

# CMD ID's
ID_COMPLETED = 0x01
ID_ACK = 0x02
ID_LIDAR_SETUP = 0x03
ID_LIDAR_READ = 0x04
ID_NOP = 0x05

# Return CMD ID's (DATA RETURN ID DEFINITIONS)
COMPLETE_NO_ERROR             = 'COMPLETE_NO_ERROR            '
COMPLETE_UNRECOGNIZED_CMD     = 'COMPLETE_UNRECOGNIZED_CMD    '
COMPLETE_NO_LIDAR_READ        = 'COMPLETE_NO_LIDAR_READ       '
COMPLETE_LIDAR_READ_DATA      = 'COMPLETE_LIDAR_READ_DATA     '
COMPLETE_CANT_SET_LIDAR       = 'COMPLETE_CANT_SET_LIDAR      '
COMPLETE_WRONG_CMD_LENGTH     = 'COMPLETE_WRONG_CMD_LENGTH    '
COMPLETE_I2C_READ_ERROR       = 'COMPLETE_I2C_READ_ERROR      '
COMPLETE_I2C_TIMEOUT          = 'COMPLETE_I2C_TIMEOUT         '
COMPLETE_LIDAR_INVALID_CONFIG = 'COMPLETE_LIDAR_INVALID_CONFIG'
COMPLETE_I2C_WRITE_ERROR      = 'COMPLETE_I2C_WRITE_ERROR     '
COMPLETE_UNKNOWN_ERROR        = 'COMPLETE_UNKNOWN_ERROR       '

COMP_RETURN_CODES = {}
COMP_RETURN_CODES[0x00] = COMPLETE_NO_ERROR            
COMP_RETURN_CODES[0x01] = COMPLETE_UNRECOGNIZED_CMD    
COMP_RETURN_CODES[0x02] = COMPLETE_NO_LIDAR_READ       
COMP_RETURN_CODES[0x03] = COMPLETE_LIDAR_READ_DATA     
COMP_RETURN_CODES[0x04] = COMPLETE_CANT_SET_LIDAR      
COMP_RETURN_CODES[0x05] = COMPLETE_WRONG_CMD_LENGTH    
COMP_RETURN_CODES[0x06] = COMPLETE_I2C_READ_ERROR      
COMP_RETURN_CODES[0x07] = COMPLETE_I2C_TIMEOUT         
COMP_RETURN_CODES[0x08] = COMPLETE_LIDAR_INVALID_CONFIG
COMP_RETURN_CODES[0x08] = COMPLETE_I2C_WRITE_ERROR     
COMP_RETURN_CODES[0xff] = COMPLETE_UNKNOWN_ERROR       

# Ack ID's
ACK_NO_ERROR = 'ACK_NO_ERROR'
ACK_HEADER_ERROR = 'ACK_HEADER_ERROR'
ACK_FOOTER_ERROR = 'ACK_FOOTER_ERROR'
ACK_SIZE_ERROR = 'ACK_SIZE_ERROR'
ACK_TIMEOUT_ERROR = 'ACK_TIMEOUT_ERROR'

ACK_RETURN_CODES = {}
ACK_RETURN_CODES[0x00] = ACK_NO_ERROR
ACK_RETURN_CODES[0x01] = ACK_HEADER_ERROR
ACK_RETURN_CODES[0x02] = ACK_FOOTER_ERROR
ACK_RETURN_CODES[0x03] = ACK_SIZE_ERROR
ACK_RETURN_CODES[0x04] = ACK_TIMEOUT_ERROR



# Completed ID's
COMPLETED_NO_ERROR = 0
COMPLETED_DATA = 1

# LIDAR DEFINITIONS

LIDAR_I2C_ADDRESS = 0x62
